{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "anime",
        "lineageTag": "ca8cc754-d218-727e-44b3-0275c18733a2",
        "columns": [
          {
            "name": "anime_id",
            "dataType": "int64",
            "sourceColumn": "anime_id",
            "lineageTag": "98dd6d2f-9ba0-592b-790f-971857cd8f38",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "title",
            "dataType": "string",
            "sourceColumn": "title",
            "lineageTag": "5870049f-ce6d-23a2-e95c-ac1adf60f41d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "type",
            "dataType": "string",
            "sourceColumn": "type",
            "lineageTag": "cc4b3274-16e1-2989-4c5d-49e4405cd602",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "episodes",
            "dataType": "double",
            "sourceColumn": "episodes",
            "lineageTag": "2cb2124e-d9ce-be60-9c2b-ddfddf713f40",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0"
          },
          {
            "name": "status",
            "dataType": "string",
            "sourceColumn": "status",
            "lineageTag": "34846e65-b08e-fdb4-bbca-e6e85725f7d3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "start_date",
            "dataType": "dateTime",
            "sourceColumn": "start_date",
            "lineageTag": "12decb5a-eedf-d1d5-5d8e-e52be1e2eaa3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "formatString": "dd-mm-yyyy"
          },
          {
            "name": "end_date",
            "dataType": "dateTime",
            "sourceColumn": "end_date",
            "lineageTag": "84bcc87a-c770-f2b9-0a2b-c10694801a36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "formatString": "dd-mm-yyyy"
          },
          {
            "name": "score",
            "dataType": "double",
            "sourceColumn": "score",
            "lineageTag": "295b2704-7bf1-e64f-e357-ac9dcec09655",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.00"
          },
          {
            "name": "members_scored",
            "dataType": "double",
            "sourceColumn": "members_scored",
            "lineageTag": "6fcb745a-0b43-1920-6bd7-c84cfa57f2b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0"
          },
          {
            "name": "rank",
            "dataType": "double",
            "sourceColumn": "rank",
            "lineageTag": "66e9e9c8-0fda-ea45-69e6-4ecca6a68878",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year",
            "lineageTag": "83a454da-00b5-fb2d-c7af-fc23289d2696",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "decade",
            "dataType": "string",
            "sourceColumn": "decade",
            "lineageTag": "05ca99af-3f69-1d90-355e-f85df201a628",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "duration_min",
            "dataType": "double",
            "sourceColumn": "duration_min",
            "lineageTag": "607732d2-c52b-b517-1db3-9a745c19785a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0.0"
          },
          {
            "name": "total_hours",
            "dataType": "double",
            "sourceColumn": "total_hours",
            "lineageTag": "9911414c-42a4-5b36-3564-b7f005250fe9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "age_rating",
            "dataType": "string",
            "sourceColumn": "age_rating",
            "lineageTag": "e039b8f6-3ece-e66f-d8ff-37c7dcd9f76a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "main_studio",
            "dataType": "string",
            "sourceColumn": "main_studio",
            "lineageTag": "f253038f-2097-60af-0604-4e101a2b8570",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "score_band",
            "dataType": "string",
            "sourceColumn": "score_band",
            "lineageTag": "c9688f91-fb02-3ae9-c8da-5139bf0d2669",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Total Titles",
            "expression": "COUNTROWS(anime)",
            "formatString": "#,0",
            "lineageTag": "a0295d3d-3361-40f6-eca4-9b4d98f1e787"
          },
          {
            "name": "Scored Titles",
            "expression": "CALCULATE(COUNTROWS(anime), NOT ISBLANK(anime[score]))",
            "formatString": "#,0",
            "lineageTag": "a46e043d-5b42-6091-2149-7ab82506c063"
          },
          {
            "name": "Average Score",
            "expression": "AVERAGE(anime[score])",
            "formatString": "0.00",
            "lineageTag": "2114a066-0657-e815-335c-7dfd2d41c50f"
          },
          {
            "name": "Highest Score",
            "expression": "MAX(anime[score])",
            "formatString": "0.00",
            "lineageTag": "f3b4ec1d-0028-cb33-108d-f4c136d5299c"
          },
          {
            "name": "Total Members",
            "expression": "SUM(anime[members_scored])",
            "formatString": "#,0",
            "lineageTag": "433c6843-53b9-53e0-5e5d-0938a517877c"
          },
          {
            "name": "High Rated Titles",
            "expression": "CALCULATE(COUNTROWS(anime), anime[score] >= 8)",
            "formatString": "#,0",
            "lineageTag": "f11ef784-f14e-8d60-78ce-4d3edae8e67b"
          },
          {
            "name": "% Rated",
            "expression": "DIVIDE([Scored Titles], [Total Titles])",
            "formatString": "0.0%",
            "lineageTag": "0e9a04f0-032b-48d5-7923-bc752e2a6e4d"
          },
          {
            "name": "Avg Episodes",
            "expression": "AVERAGE(anime[episodes])",
            "formatString": "0.0",
            "lineageTag": "b6f16ecb-fb4f-25b3-dff4-aff9c774eeb7"
          },
          {
            "name": "Total Runtime Hours",
            "expression": "SUM(anime[total_hours])",
            "formatString": "#,0",
            "lineageTag": "f9116c53-96bd-7f17-4630-2abd977ca3c5"
          },
          {
            "name": "Avg Members per Title",
            "expression": "DIVIDE([Total Members], [Scored Titles])",
            "formatString": "#,0",
            "lineageTag": "aff298a5-1c4a-9a6c-3af3-8910926c9b31"
          },
          {
            "name": "Weighted Avg Score",
            "expression": "DIVIDE(SUMX(anime, anime[score] * anime[members_scored]), [Total Members])",
            "formatString": "0.00",
            "lineageTag": "3fbf4aab-fe78-620b-3b13-6dab3181b57f"
          },
          {
            "name": "Currently Airing",
            "expression": "CALCULATE(COUNTROWS(anime), anime[status] = \"Currently Airing\")",
            "formatString": "#,0",
            "lineageTag": "38388ca1-c9b9-29fc-e5c4-e0ca5fe0f1fe"
          }
        ],
        "partitions": [
          {
            "name": "anime",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AnimeClean,",
                "    SelectedColumns = Table.SelectColumns(Source, {\"anime_id\", \"title\", \"type\", \"episodes\", \"status\", \"start_date\", \"end_date\", \"score\", \"members_scored\", \"rank\", \"year\", \"decade\", \"duration_min\", \"total_hours\", \"age_rating\", \"main_studio\", \"score_band\"})",
                "in",
                "    SelectedColumns"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "anime_genres",
        "lineageTag": "1325ea6f-2634-2607-d6a2-ba0e1819d3de",
        "columns": [
          {
            "name": "anime_id",
            "dataType": "int64",
            "sourceColumn": "anime_id",
            "lineageTag": "c8f38273-89b5-4c1e-4bb8-6f3a99fae49b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "formatString": "0"
          },
          {
            "name": "genre",
            "dataType": "string",
            "sourceColumn": "genre",
            "lineageTag": "8463ea0c-003a-17ee-f5c6-63ba5fae37ee",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Genre Tags",
            "expression": "COUNTROWS(anime_genres)",
            "formatString": "#,0",
            "lineageTag": "8fd39b33-25bb-d595-69d9-729597d6d6cf"
          }
        ],
        "partitions": [
          {
            "name": "anime_genres",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = AnimeClean,",
                "    GenreSource = Table.SelectColumns(Source, {\"anime_id\", \"genres\"}),",
                "    SplitToList = Table.TransformColumns(GenreSource, {{\"genres\", each Text.Split(_, \", \")}}),",
                "    ExpandedRows = Table.ExpandListColumn(SplitToList, \"genres\"),",
                "    Renamed = Table.RenameColumns(ExpandedRows, {{\"genres\", \"genre\"}}),",
                "    Typed = Table.TransformColumnTypes(Renamed, {{\"anime_id\", Int64.Type}, {\"genre\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "84826410-e290-f162-92ec-7b59200a3a47",
        "fromTable": "anime_genres",
        "fromColumn": "anime_id",
        "toTable": "anime",
        "toColumn": "anime_id",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "expressions": [
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": "\"D:\\DVT\\Exp-6b\\\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "lineageTag": "eca07335-a33c-5aeb-5e1b-c7c98b4b9d80",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "AnimeClean",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(DataFolder & \"popular_anime.csv\"), [Delimiter=\",\", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    RemovedColumns = Table.RemoveColumns(PromotedHeaders, {\"producers\", \"image\", \"trailer\", \"synopsis\"}),",
          "    BlanksToNull = Table.ReplaceValue(RemovedColumns, \"\", null, Replacer.ReplaceValue, {\"genres\", \"type\", \"episodes\", \"aired_from\", \"aired_to\", \"score\", \"scored_by\", \"rank\", \"rating\", \"studios\"}),",
          "    ChangedType = Table.TransformColumnTypes(BlanksToNull, {{\"id\", Int64.Type}, {\"name\", type text}, {\"episodes\", type number}, {\"score\", type number}, {\"scored_by\", type number}, {\"rank\", type number}}, \"en-US\"),",
          "    RemovedDuplicates = Table.Distinct(ChangedType, {\"id\"}),",
          "    RemovedAdult = Table.SelectRows(RemovedDuplicates, each [rating] <> \"Rx - Hentai\" and not Text.Contains(if [genres] = null then \"\" else [genres], \"Hentai\") and not Text.Contains(if [genres] = null then \"\" else [genres], \"Erotica\")),",
          "    RemovedBlankType = Table.SelectRows(RemovedAdult, each [type] <> null),",
          "    TrimmedText = Table.TransformColumns(RemovedBlankType, {{\"name\", Text.Trim, type text}, {\"duration_per_ep\", Text.Trim, type text}}),",
          "    ParsedDates = Table.TransformColumns(TrimmedText, {{\"aired_from\", each if _ = null then null else Date.FromText(Text.Start(_, 10)), type date}, {\"aired_to\", each if _ = null then null else Date.FromText(Text.Start(_, 10)), type date}}),",
          "    AddedYear = Table.AddColumn(ParsedDates, \"year\", each if [aired_from] = null then null else Date.Year([aired_from]), Int64.Type),",
          "    AddedDecade = Table.AddColumn(AddedYear, \"decade\", each if [year] = null then \"Unknown\" else Text.From(Number.IntegerDivide([year], 10) * 10) & \"s\", type text),",
          "    AddedDuration = Table.AddColumn(AddedDecade, \"duration_min\", each let t = Text.Replace([duration_per_ep], \" per ep\", \"\"), w = Text.Split(t, \" \"),",
          "            hr = if List.Contains(w, \"hr\") then Number.From(w{List.PositionOf(w, \"hr\") - 1}) else 0,",
          "            mn = if List.Contains(w, \"min\") then Number.From(w{List.PositionOf(w, \"min\") - 1}) else 0,",
          "            sc = if List.Contains(w, \"sec\") then Number.From(w{List.PositionOf(w, \"sec\") - 1}) else 0",
          "        in if t = \"Unknown\" then null else hr * 60 + mn + sc / 60, type number),",
          "    FilledEpisodes = Table.ReplaceValue(AddedDuration, null, 1, Replacer.ReplaceValue, {\"episodes\"}),",
          "    AddedRuntime = Table.AddColumn(FilledEpisodes, \"total_hours\", each if [duration_min] = null then null else Number.Round([episodes] * [duration_min] / 60, 2), type number),",
          "    AgeRating = Table.AddColumn(AddedRuntime, \"age_rating\", each if [rating] = null then \"PG-13\" else Text.BeforeDelimiter([rating], \" - \"), type text),",
          "    MainStudio = Table.AddColumn(AgeRating, \"main_studio\", each if [studios] = null then \"Unknown\" else Text.BeforeDelimiter([studios], \", \"), type text),",
          "    GenresFilled = Table.ReplaceValue(MainStudio, null, \"Unknown\", Replacer.ReplaceValue, {\"genres\"}),",
          "    ScoreBand = Table.AddColumn(GenresFilled, \"score_band\", each if [score] = null then \"Not Rated\" else if [score] >= 8 then \"Excellent (8+)\" else if [score] >= 7 then \"Very Good (7-8)\" else if [score] >= 6 then \"Good (6-7)\" else if [score] >= 5 then \"Average (5-6)\" else \"Poor (<5)\", type text),",
          "    Renamed = Table.RenameColumns(ScoreBand, {{\"id\", \"anime_id\"}, {\"name\", \"title\"}, {\"scored_by\", \"members_scored\"}, {\"aired_from\", \"start_date\"}, {\"aired_to\", \"end_date\"}})",
          "in",
          "    Renamed"
        ],
        "lineageTag": "05e7323c-540e-ca71-6bce-cb63897bd821",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DataFolder\", \"AnimeClean\", \"anime\", \"anime_genres\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.157.151.0"
      }
    ]
  }
}